In [1]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Global_Superstore2.csv to Global_Superstore2.csv

In [3]:
import os

print(os.listdir())

['.config', 'Global_Superstore2.csv', 'sample_data']

In [5]:
file_path = "Global_Superstore2.csv"

df = pd.read_csv(file_path, encoding="latin1")

print("Dataset extracted successfully!")

Dataset extracted successfully!

In [6]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

display(df.head())

Rows: 51290
Columns: 24

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [7]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country', 'Postal Code', 'Market', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Cost', 'Order Priority']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(17)
memory usage: 9.4+ MB

In [9]:
print(df.isnull().sum())

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [11]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Number of rows: 51290
Number of columns: 24

Column names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country', 'Postal Code', 'Market', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Cost', 'Order Priority']

First 5 rows:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [12]:
print("\nDataset information:")
df.info()

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(17)
memory usage: 9.4+ MB

In [13]:
print("\nMissing values:")
print(df.isnull().sum())

Missing values:
Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [14]:
print("\nDuplicate rows:")
print(df.duplicated().sum())

Duplicate rows:
0

In [15]:
# ============================================================
# ETL - GLOBAL SUPERSTORE DATASET
# Step 01: EXTRACT
# ============================================================

import pandas as pd
import numpy as np

# Load the dataset
file_path = "Global_Superstore2.csv"

df = pd.read_csv(file_path, encoding="latin1")

print("Dataset extracted successfully!")

# Display basic information
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

# Display first 5 records
display(df.head())

Dataset extracted successfully!
Number of rows: 51290
Number of columns: 24

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [16]:
# ============================================================
# STEP 02: DATA PROFILING
# ============================================================

print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nStatistical Summary:")
display(df.describe(include="all"))

Dataset Shape:
(51290, 24)

Column Names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country', 'Postal Code', 'Market', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Cost', 'Order Priority']

Data Types:
Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
City               object
State              object
Country            object
Postal Code       float64
Market             object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
Shipping Cost     float64
Order Priority     object
dtype: object

Missing Values:
Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
count,51290.00000,51290,51290,51290,51290,51290,51290,51290,51290,51290,...,51290,51290,51290,51290,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290
unique,NaN,25035,1430,1464,4,1590,795,3,3636,1094,...,10292,3,17,3788,NaN,NaN,NaN,NaN,NaN,4
top,NaN,CA-2014-100111,18-06-2014,22-11-2014,Standard Class,PO-18850,Muhammed Yedwab,Consumer,New York City,California,...,OFF-AR-10003651,Office Supplies,Binders,Staples,NaN,NaN,NaN,NaN,NaN,Medium
freq,NaN,14,135,130,30775,97,108,26518,915,2001,...,35,31273,6152,227,NaN,NaN,NaN,NaN,NaN,29433
mean,25645.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,246.490581,3.476545,0.142908,28.610982,26.375915,NaN
std,14806.29199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,487.565361,2.278766,0.212280,174.340972,57.296804,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000,0.000000,NaN
25%,12823.25000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,30.758625,2.000000,0.000000,0.000000,2.610000,NaN
50%,25645.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,85.053000,3.000000,0.000000,9.240000,7.790000,NaN
75%,38467.75000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,251.053200,5.000000,0.200000,36.810000,24.450000,NaN
max,51290.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.850000,8399.976000,933.570000,NaN

In [17]:
# ============================================================
# STEP 03: DATA QUALITY CHECK
# ============================================================

# Check unique values in categorical columns
categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    print(f"\n{'='*60}")
    print(f"Column: {column}")
    print("Unique values:", df[column].nunique())
    print(df[column].dropna().unique()[:20])

============================================================
Column: Order ID
Unique values: 25035
['CA-2012-124891' 'IN-2013-77878' 'IN-2013-71249' 'ES-2013-1579342'
 'SG-2013-4320' 'IN-2013-42360' 'IN-2011-81826' 'IN-2012-86369'
 'CA-2014-135909' 'CA-2012-116638' 'CA-2011-102988' 'ID-2012-28402'
 'SA-2011-1830' 'MX-2012-130015' 'IN-2013-73951' 'ES-2014-5099955'
 'CA-2014-143567' 'ES-2014-1651774' 'IN-2014-11763' 'TZ-2014-8190']

============================================================
Column: Order Date
Unique values: 1430
['31-07-2012' '05-02-2013' '17-10-2013' '28-01-2013' '05-11-2013'
 '28-06-2013' '07-11-2011' '14-04-2012' '14-10-2014' '28-01-2012'
 '05-04-2011' '19-04-2012' '27-12-2011' '13-11-2012' '06-06-2013'
 '31-07-2014' '03-11-2014' '08-09-2014' '31-01-2014' '05-12-2014']

============================================================
Column: Ship Date
Unique values: 1464
['31-07-2012' '07-02-2013' '18-10-2013' '30-01-2013' '06-11-2013'
 '01-07-2013' '09-11-2011' '18-04-2012' '21-10-2014' '31-01-2012'
 '09-04-2011' '22-04-2012' '29-12-2011' '13-11-2012' '08-06-2013'
 '03-08-2014' '06-11-2014' '14-09-2014' '01-02-2014' '07-12-2014']

============================================================
Column: Ship Mode
Unique values: 4
['Same Day' 'Second Class' 'First Class' 'Standard Class']

============================================================
Column: Customer ID
Unique values: 1590
['RH-19495' 'JR-16210' 'CR-12730' 'KM-16375' 'RH-9495' 'JM-15655'
 'TS-21340' 'MB-18085' 'JW-15220' 'JH-15985' 'GM-14695' 'AJ-10780'
 'MM-7260' 'VF-21715' 'PF-19120' 'BP-11185' 'TB-21175' 'PJ-18835'
 'JS-15685' 'RH-9555']

============================================================
Column: Customer Name
Unique values: 795
['Rick Hansen' 'Justin Ritter' 'Craig Reiter' 'Katherine Murray'
 'Jim Mitchum' 'Toby Swindell' 'Mick Brown' 'Jane Waco' 'Joseph Holt'
 'Greg Maxwell' 'Anthony Jacobs' 'Magdelene Morse' 'Vicky Freymann'
 'Peter Fuller' 'Ben Peterman' 'Thomas Boland' 'Patrick Jones' 'Jim Sink'
 'Ritsa Hightower' 'Ann Blume']

============================================================
Column: Segment
Unique values: 3
['Consumer' 'Corporate' 'Home Office']

============================================================
Column: City
Unique values: 3636
['New York City' 'Wollongong' 'Brisbane' 'Berlin' 'Dakar' 'Sydney'
 'Porirua' 'Hamilton' 'Sacramento' 'Concord' 'Alexandria' 'Kabul' 'Jizan'
 'Toledo' 'Mudanjiang' 'Paris' 'Henderson' 'Prato' 'Townsville' 'Uvinza']

============================================================
Column: State
Unique values: 1094
['New York' 'New South Wales' 'Queensland' 'Berlin' 'Dakar' 'Wellington'
 'Waikato' 'California' 'North Carolina' 'Virginia' 'Kabul' 'Jizan'
 'Parana' 'Heilongjiang' 'Ile-de-France' 'Kentucky' 'Tuscany' 'Kigoma'
 'Silesia' 'Illinois']

============================================================
Column: Country
Unique values: 147
['United States' 'Australia' 'Germany' 'Senegal' 'New Zealand'
 'Afghanistan' 'Saudi Arabia' 'Brazil' 'China' 'France' 'Italy' 'Tanzania'
 'Poland' 'United Kingdom' 'Mexico' 'El Salvador' 'Taiwan' 'India'
 'Dominican Republic' 'Democratic Republic of the Congo']

============================================================
Column: Market
Unique values: 7
['US' 'APAC' 'EU' 'Africa' 'EMEA' 'LATAM' 'Canada']

============================================================
Column: Region
Unique values: 13
['East' 'Oceania' 'Central' 'Africa' 'West' 'South' 'Central Asia' 'EMEA'
 'North Asia' 'North' 'Caribbean' 'Southeast Asia' 'Canada']

============================================================
Column: Product ID
Unique values: 10292
['TEC-AC-10003033' 'FUR-CH-10003950' 'TEC-PH-10004664' 'TEC-PH-10004583'
 'TEC-SHA-10000501' 'TEC-PH-10000030' 'FUR-CH-10004050' 'FUR-TA-10002958'
 'OFF-BI-10003527' 'FUR-TA-10000198' 'OFF-SU-10002881' 'FUR-TA-10001889'
 'TEC-CIS-10001717' 'FUR-CH-10002033' 'OFF-AP-10003500' 'OFF-AP-10000423'
 'TEC-AC-10004145' 'OFF-AP-10004512' 'TEC-CO-10000865' 'OFF-KIT-10004058']

============================================================
Column: Category
Unique values: 3
['Technology' 'Furniture' 'Office Supplies']

============================================================
Column: Sub-Category
Unique values: 17
['Accessories' 'Chairs' 'Phones' 'Copiers' 'Tables' 'Binders' 'Supplies'
 'Appliances' 'Machines' 'Bookcases' 'Storage' 'Furnishings' 'Art' 'Paper'
 'Envelopes' 'Fasteners' 'Labels']

============================================================
Column: Product Name
Unique values: 3788
['Plantronics CS510 - Over-the-Head monaural Wireless Headset System'
 'Novimex Executive Leather Armchair, Black'
 'Nokia Smart Phone, with Caller ID' 'Motorola Smart Phone, Cordless'
 'Sharp Wireless Fax, High-Speed' 'Samsung Smart Phone, with Caller ID'
 'Novimex Executive Leather Armchair, Adjustable'
 'Chromcraft Conference Table, Fully Assembled'
 'Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind'
 'Chromcraft Bull-Nose Wood Oval Conference Tables & Bases'
 'Martin Yale Chadless Opener Electric Letter Opener'
 'Bevis Conference Table, Fully Assembled'
 'Cisco Smart Phone, with Caller ID'
 'Harbour Creations Executive Leather Armchair, Adjustable'
 'KitchenAid Microwave, White' 'Breville Refrigerator, Red'
 'Logitech diNovo Edge Keyboard' 'Hoover Stove, Red'
 'Brother Fax Machine, High-Speed' 'KitchenAid Stove, White']

============================================================
Column: Order Priority
Unique values: 4
['Critical' 'Medium' 'High' 'Low']

In [18]:
# Check numeric columns
numeric_columns = df.select_dtypes(include=np.number).columns

print("Numeric Columns:")
print(numeric_columns.tolist())

display(df[numeric_columns].describe())

Numeric Columns:
['Row ID', 'Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Cost']

,Row ID,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost
count,51290.00000,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,55190.379428,246.490581,3.476545,0.142908,28.610982,26.375915
std,14806.29199,32063.693350,487.565361,2.278766,0.212280,174.340972,57.296804
min,1.00000,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.000000
25%,12823.25000,23223.000000,30.758625,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,56430.500000,85.053000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,90008.000000,251.053200,5.000000,0.200000,36.810000,24.450000
max,51290.00000,99301.000000,22638.480000,14.000000,0.850000,8399.976000,933.570000

In [19]:
# Check columns containing "date"
date_columns = [col for col in df.columns if "date" in col.lower()]

print("Possible date columns:")
print(date_columns)

Possible date columns:
['Order Date', 'Ship Date']

In [20]:
for column in date_columns:
    print(f"\n{column}")
    print(df[column].head())

Order Date
0    31-07-2012
1    05-02-2013
2    17-10-2013
3    28-01-2013
4    05-11-2013
Name: Order Date, dtype: object

Ship Date
0    31-07-2012
1    07-02-2013
2    18-10-2013
3    30-01-2013
4    06-11-2013
Name: Ship Date, dtype: object

In [21]:
# ============================================================
# STEP 03: DATA TRANSFORMATION
# ============================================================

# Create a copy of the raw dataset
df_clean = df.copy()

print("Original rows:", len(df_clean))

Original rows: 51290

In [22]:
# Remove duplicate rows
duplicates = df_clean.duplicated().sum()

print("Duplicate rows found:", duplicates)

df_clean = df_clean.drop_duplicates()

print("Rows after removing duplicates:", len(df_clean))

Duplicate rows found: 0
Rows after removing duplicates: 51290

In [23]:
# Remove leading/trailing spaces from text columns

text_columns = df_clean.select_dtypes(include="object").columns

for column in text_columns:
    df_clean[column] = df_clean[column].str.strip()

print("Text values standardized successfully.")

Text values standardized successfully.

In [24]:
# Identify date columns
date_columns = [col for col in df_clean.columns if "date" in col.lower()]

print("Date columns:", date_columns)

Date columns: ['Order Date', 'Ship Date']

In [27]:
# ============================================================
# TRANSFORMATION: DATE STANDARDIZATION
# ============================================================

date_columns = ["Order Date", "Ship Date"]

for column in date_columns:
    df_clean[column] = pd.to_datetime(
        df_clean[column],
        dayfirst=True,
        errors="coerce"
    )

print("Date columns converted successfully.")

for column in date_columns:
    print(column, ":", df_clean[column].dtype)

Date columns converted successfully.
Order Date : datetime64[ns]
Ship Date : datetime64[ns]

In [28]:
# Check the converted dates
display(df_clean[["Order Date", "Ship Date"]].head(10))

  Order Date  Ship Date
0 2012-07-31 2012-07-31
1 2013-02-05 2013-02-07
2 2013-10-17 2013-10-18
3 2013-01-28 2013-01-30
4 2013-11-05 2013-11-06
5 2013-06-28 2013-07-01
6 2011-11-07 2011-11-09
7 2012-04-14 2012-04-18
8 2014-10-14 2014-10-21
9 2012-01-28 2012-01-31

In [29]:
# ============================================================
# CHECK MISSING VALUES AFTER TRANSFORMATION
# ============================================================

missing_values = df_clean.isnull().sum()

print("Missing values in each column:")
print(missing_values[missing_values > 0])

Missing values in each column:
Postal Code    41296
dtype: int64

In [30]:
# ============================================================
# TRANSFORMATION: HANDLE MISSING POSTAL CODES
# ============================================================

# Convert Postal Code to string
df_clean["Postal Code"] = df_clean["Postal Code"].astype("Int64").astype("string")

# Replace missing postal codes
df_clean["Postal Code"] = df_clean["Postal Code"].fillna("Unknown")

print("Missing Postal Codes after transformation:")
print(df_clean["Postal Code"].isnull().sum())

print("\nPostal Code sample:")
print(df_clean["Postal Code"].head(10))

Missing Postal Codes after transformation:
0

Postal Code sample:
0      10024
1    Unknown
2    Unknown
3    Unknown
4    Unknown
5    Unknown
6    Unknown
7    Unknown
8      95823
9      28027
Name: Postal Code, dtype: string

In [31]:
# ============================================================
# TRANSFORMATION: CHECK INVALID NUMERIC VALUES
# ============================================================

numeric_columns = df_clean.select_dtypes(include=np.number).columns

for column in numeric_columns:
    negative_count = (df_clean[column] < 0).sum()
    zero_count = (df_clean[column] == 0).sum()

    print(f"{column}")
    print(f"  Negative values: {negative_count}")
    print(f"  Zero values: {zero_count}")

Row ID
  Negative values: 0
  Zero values: 0
Sales
  Negative values: 0
  Zero values: 0
Quantity
  Negative values: 0
  Zero values: 0
Discount
  Negative values: 0
  Zero values: 29009
Profit
  Negative values: 12544
  Zero values: 668
Shipping Cost
  Negative values: 0
  Zero values: 2

In [32]:
# ============================================================
# CHECK SHIPPING COST VALUES
# ============================================================

print("Records with zero Shipping Cost:")
display(df_clean[df_clean["Shipping Cost"] == 0])

Records with zero Shipping Cost:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
51288,9596,MX-2012-140767,2012-02-18,2012-02-22,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.44,2,0.0,2.4,0.0,Medium
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.38,3,0.0,1.8,0.0,High

In [33]:
# Check negative profit records
print("Number of negative profit records:")
print((df_clean["Profit"] < 0).sum())

print("\nSample negative profit records:")
display(df_clean[df_clean["Profit"] < 0][
    ["Sales", "Quantity", "Discount", "Shipping Cost", "Profit"]
].head(10))

Number of negative profit records:
12544

Sample negative profit records:

        Sales  Quantity  Discount  Shipping Cost     Profit
1   3709.3950         9      0.10         923.63  -288.7650
3   2892.5100         5      0.10         910.16   -96.5400
9   4297.6440        13      0.40         865.74 -1862.3124
30  1696.6400         5      0.20         704.06  -148.4600
32  2453.4300         5      0.30         690.42  -350.4900
37  7999.9800         4      0.50         674.82 -3839.9904
40  3200.5962         6      0.17         660.87   -77.2038
73  3427.1496         7      0.47         586.57  -452.8104
83  4416.1740         9      0.30         566.65  -630.8820
85  2487.8088         6      0.17         562.14  -269.7912

In [34]:
# ============================================================
# TRANSFORMATION: CREATE DATE DIMENSIONS
# ============================================================

# Create Year
df_clean["Order Year"] = df_clean["Order Date"].dt.year

# Create Month
df_clean["Order Month"] = df_clean["Order Date"].dt.month

# Create Month Name
df_clean["Order Month Name"] = df_clean["Order Date"].dt.month_name()

# Create Quarter
df_clean["Order Quarter"] = df_clean["Order Date"].dt.quarter

# Create Year-Month
df_clean["Order Year-Month"] = df_clean["Order Date"].dt.to_period("M").astype(str)

print("Date-based columns created successfully!")

display(df_clean[
    ["Order Date", "Order Year", "Order Month",
     "Order Month Name", "Order Quarter", "Order Year-Month"]
].head(10))

Date-based columns created successfully!

,Order Date,Order Year,Order Month,Order Month Name,Order Quarter,Order Year-Month
0,2012-07-31,2012,7,July,3,2012-07
1,2013-02-05,2013,2,February,1,2013-02
2,2013-10-17,2013,10,October,4,2013-10
3,2013-01-28,2013,1,January,1,2013-01
4,2013-11-05,2013,11,November,4,2013-11
5,2013-06-28,2013,6,June,2,2013-06
6,2011-11-07,2011,11,November,4,2011-11
7,2012-04-14,2012,4,April,2,2012-04
8,2014-10-14,2014,10,October,4,2014-10
9,2012-01-28,2012,1,January,1,2012-01

In [35]:
# ============================================================
# TRANSFORMATION: CALCULATE PROFIT MARGIN
# ============================================================

df_clean["Profit Margin"] = (
    df_clean["Profit"] / df_clean["Sales"]
) * 100

print("Profit Margin calculated successfully!")

display(df_clean[
    ["Sales", "Profit", "Profit Margin"]
].head(10))

Profit Margin calculated successfully!

      Sales     Profit  Profit Margin
0  2309.650   762.1845      33.000000
1  3709.395  -288.7650      -7.784693
2  5175.171   919.9710      17.776630
3  2892.510   -96.5400      -3.337586
4  2832.960   311.5200      10.996272
5  2862.675   763.2750      26.662999
6  1822.080   564.8400      30.999737
7  5244.840   996.4800      18.999245
8  5083.960  1906.4850      37.500000
9  4297.644 -1862.3124     -43.333333

In [36]:
# ============================================================
# FINAL TRANSFORMATION CHECK
# ============================================================

print("Original dataset shape:", df.shape)
print("Transformed dataset shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isnull().sum()[df_clean.isnull().sum() > 0])

print("\nDuplicate rows:")
print(df_clean.duplicated().sum())

print("\nFinal columns:")
print(df_clean.columns.tolist())

Original dataset shape: (51290, 24)
Transformed dataset shape: (51290, 30)

Missing values:
Series([], dtype: int64)

Duplicate rows:
0

Final columns:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country', 'Postal Code', 'Market', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Cost', 'Order Priority', 'Order Year', 'Order Month', 'Order Month Name', 'Order Quarter', 'Order Year-Month', 'Profit Margin']

In [37]:
# ============================================================
# STEP 04: LOAD
# ============================================================

output_file = "Global_Superstore_Cleaned.csv"

df_clean.to_csv(output_file, index=False)

print("Data loaded successfully!")
print("Output file:", output_file)

Data loaded successfully!
Output file: Global_Superstore_Cleaned.csv

In [38]:
# ============================================================
# LOAD VERIFICATION
# ============================================================

df_loaded = pd.read_csv(
    "Global_Superstore_Cleaned.csv",
    encoding="utf-8"
)

print("Loaded dataset successfully!")
print("Rows:", df_loaded.shape[0])
print("Columns:", df_loaded.shape[1])

display(df_loaded.head())

Loaded dataset successfully!
Rows: 51290
Columns: 30

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Discount,Profit,Shipping Cost,Order Priority,Order Year,Order Month,Order Month Name,Order Quarter,Order Year-Month,Profit Margin
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,0.0,762.1845,933.57,Critical,2012,7,July,3,2012-07,33.000000
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,0.1,-288.7650,923.63,Critical,2013,2,February,1,2013-02,-7.784693
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,0.1,919.9710,915.49,Medium,2013,10,October,4,2013-10,17.776630
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,0.1,-96.5400,910.16,Medium,2013,1,January,1,2013-01,-3.337586
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,0.0,311.5200,903.04,Critical,2013,11,November,4,2013-11,10.996272

In [39]:
# ============================================================
# ETL FINAL VERIFICATION
# ============================================================

print("========== ETL SUMMARY ==========")

print("Original rows:", df.shape[0])
print("Final rows:", df_loaded.shape[0])

print("Original columns:", df.shape[1])
print("Final columns:", df_loaded.shape[1])

print("\nETL pipeline completed successfully!")

========== ETL SUMMARY ==========
Original rows: 51290
Final rows: 51290
Original columns: 24
Final columns: 30

ETL pipeline completed successfully!

In [40]:
# ============================================================
# STEP 05: FINAL ETL VALIDATION
# ============================================================

print("========== FINAL ETL VALIDATION ==========")

# 1. Check row and column counts
print("\n1. Dataset Shape")
print("Rows:", df_loaded.shape[0])
print("Columns:", df_loaded.shape[1])

# 2. Check missing values
print("\n2. Missing Values")
missing = df_loaded.isnull().sum()
print(missing[missing > 0])

# 3. Check duplicate records
print("\n3. Duplicate Records")
print("Duplicates:", df_loaded.duplicated().sum())

# 4. Check data types
print("\n4. Data Types")
print(df_loaded.dtypes)

# 5. Display final data
print("\n5. Final Dataset Preview")
display(df_loaded.head())

print("\n========== ETL PROCESS COMPLETED ==========")

========== FINAL ETL VALIDATION ==========

1. Dataset Shape
Rows: 51290
Columns: 30

2. Missing Values
Series([], dtype: int64)

3. Duplicate Records
Duplicates: 0

4. Data Types
Row ID                int64
Order ID             object
Order Date           object
Ship Date            object
Ship Mode            object
Customer ID          object
Customer Name        object
Segment              object
City                 object
State                object
Country              object
Postal Code          object
Market               object
Region               object
Product ID           object
Category             object
Sub-Category         object
Product Name         object
Sales               float64
Quantity              int64
Discount            float64
Profit              float64
Shipping Cost       float64
Order Priority       object
Order Year            int64
Order Month           int64
Order Month Name     object
Order Quarter         int64
Order Year-Month     object
Profit Margin       float64
dtype: object

5. Final Dataset Preview

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Discount,Profit,Shipping Cost,Order Priority,Order Year,Order Month,Order Month Name,Order Quarter,Order Year-Month,Profit Margin
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,0.0,762.1845,933.57,Critical,2012,7,July,3,2012-07,33.000000
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,0.1,-288.7650,923.63,Critical,2013,2,February,1,2013-02,-7.784693
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,0.1,919.9710,915.49,Medium,2013,10,October,4,2013-10,17.776630
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,0.1,-96.5400,910.16,Medium,2013,1,January,1,2013-01,-3.337586
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,0.0,311.5200,903.04,Critical,2013,11,November,4,2013-11,10.996272

========== ETL PROCESS COMPLETED ==========

In [41]:
# ============================================================
# STEP 06: GENERATE ETL REPORT
# ============================================================

print("=" * 70)
print("              GLOBAL SUPERSTORE ETL REPORT")
print("=" * 70)

# Dataset information
print("\n1. DATASET INFORMATION")
print("-" * 70)
print("Dataset Name       : Global Superstore")
print("Original Rows      :", df.shape[0])
print("Original Columns   :", df.shape[1])

# Profiling results
print("\n2. DATA PROFILING")
print("-" * 70)

print("Duplicate Rows     :", df.duplicated().sum())

missing = df.isnull().sum()
print("Missing Values:")
print(missing[missing > 0])

# Transformation results
print("\n3. TRANSFORMATION")
print("-" * 70)

print("Duplicate rows removed")
print("Text fields standardized")
print("Order Date converted to datetime")
print("Ship Date converted to datetime")
print("Missing Postal Codes replaced with 'Unknown'")
print("Order Year created")
print("Order Month created")
print("Order Month Name created")
print("Order Quarter created")
print("Order Year-Month created")
print("Profit Margin calculated")

# Final dataset
print("\n4. FINAL DATASET")
print("-" * 70)

print("Final Rows        :", df_loaded.shape[0])
print("Final Columns     :", df_loaded.shape[1])
print("Remaining Duplicates:", df_loaded.duplicated().sum())

remaining_missing = df_loaded.isnull().sum().sum()
print("Remaining Missing Values:", remaining_missing)

# Load information
print("\n5. LOAD")
print("-" * 70)
print("Output File       : Global_Superstore_Cleaned.csv")
print("Load Status       : SUCCESS")

# Final status
print("\n" + "=" * 70)
print("              ETL PROCESS COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
              GLOBAL SUPERSTORE ETL REPORT
======================================================================

1. DATASET INFORMATION
----------------------------------------------------------------------
Dataset Name       : Global Superstore
Original Rows      : 51290
Original Columns   : 24

2. DATA PROFILING
----------------------------------------------------------------------
Duplicate Rows     : 0
Missing Values:
Postal Code    41296
dtype: int64

3. TRANSFORMATION
----------------------------------------------------------------------
Duplicate rows removed
Text fields standardized
Order Date converted to datetime
Ship Date converted to datetime
Missing Postal Codes replaced with 'Unknown'
Order Year created
Order Month created
Order Month Name created
Order Quarter created
Order Year-Month created
Profit Margin calculated

4. FINAL DATASET
----------------------------------------------------------------------
Final Rows        : 51290
Final Columns     : 30
Remaining Duplicates: 0
Remaining Missing Values: 0

5. LOAD
----------------------------------------------------------------------
Output File       : Global_Superstore_Cleaned.csv
Load Status       : SUCCESS

======================================================================
              ETL PROCESS COMPLETED SUCCESSFULLY
======================================================================

In [42]:
# ============================================================
# STEP 06: GENERATE ETL REPORT AS PDF
# ============================================================

# Install ReportLab if needed
!pip -q install reportlab

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)
from reportlab.lib.units import inch
from google.colab import files
import pandas as pd
import os


# ============================================================
# REPORT SETTINGS
# ============================================================

output_pdf = "Global_Superstore_ETL_Report.pdf"

doc = SimpleDocTemplate(
    output_pdf,
    pagesize=A4,
    rightMargin=40,
    leftMargin=40,
    topMargin=40,
    bottomMargin=40
)

styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    "TitleStyle",
    parent=styles["Title"],
    alignment=TA_CENTER,
    fontSize=20,
    leading=24,
    spaceAfter=20
)

heading_style = ParagraphStyle(
    "HeadingStyle",
    parent=styles["Heading2"],
    fontSize=14,
    leading=18,
    spaceBefore=12,
    spaceAfter=8
)

body_style = ParagraphStyle(
    "BodyStyle",
    parent=styles["BodyText"],
    fontSize=10,
    leading=14,
    spaceAfter=6
)


# ============================================================
# CALCULATE REPORT VALUES
# ============================================================

original_rows = df.shape[0]
original_columns = df.shape[1]

duplicate_count = df.duplicated().sum()

missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]

transformed_rows = df_clean.shape[0]
transformed_columns = df_clean.shape[1]

final_rows = df_loaded.shape[0]
final_columns = df_loaded.shape[1]

final_duplicates = df_loaded.duplicated().sum()

final_missing = df_loaded.isnull().sum().sum()

negative_profit = (df_clean["Profit"] < 0).sum()

zero_discount = (df_clean["Discount"] == 0).sum()


# ============================================================
# CREATE REPORT CONTENT
# ============================================================

story = []


# ------------------------------------------------------------
# TITLE
# ------------------------------------------------------------

story.append(
    Paragraph(
        "GLOBAL SUPERSTORE ETL REPORT",
        title_style
    )
)

story.append(
    Paragraph(
        "Extract, Transform and Load Process",
        ParagraphStyle(
            "Subtitle",
            parent=body_style,
            alignment=TA_CENTER,
            fontSize=11
        )
    )
)

story.append(Spacer(1, 20))


# ------------------------------------------------------------
# 1. INTRODUCTION
# ------------------------------------------------------------

story.append(
    Paragraph(
        "1. Introduction",
        heading_style
    )
)

story.append(
    Paragraph(
        "This report documents the ETL (Extract, Transform and Load) "
        "process performed on the Global Superstore dataset. The dataset "
        "was processed using Python and Pandas in Google Colab. The main "
        "objective was to extract the raw data, profile its quality, "
        "perform appropriate transformations, load the cleaned dataset, "
        "and validate the final result.",
        body_style
    )
)


# ------------------------------------------------------------
# 2. DATASET INFORMATION
# ------------------------------------------------------------

story.append(
    Paragraph(
        "2. Dataset Information",
        heading_style
    )
)

dataset_table = [
    ["Property", "Value"],
    ["Dataset", "Global Superstore"],
    ["Source", "Kaggle"],
    ["Original Rows", str(original_rows)],
    ["Original Columns", str(original_columns)],
    ["Final Rows", str(final_rows)],
    ["Final Columns", str(final_columns)]
]

table = Table(dataset_table, colWidths=[2.5 * inch, 3.5 * inch])

table.setStyle(
    TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6)
    ])
)

story.append(table)


# ------------------------------------------------------------
# 3. EXTRACT
# ------------------------------------------------------------

story.append(
    Paragraph(
        "3. Extract",
        heading_style
    )
)

story.append(
    Paragraph(
        "The raw Global Superstore CSV file was uploaded to Google "
        "Colab and extracted into a Pandas DataFrame. The dataset "
        "required Latin-1 encoding during extraction because the "
        "original CSV contained characters that could not be decoded "
        "using UTF-8.",
        body_style
    )
)

extract_table = [
    ["Item", "Result"],
    ["Input File", "Global_Superstore2.csv"],
    ["Encoding Used", "Latin-1"],
    ["Extraction Status", "Successful"],
    ["Rows Extracted", str(original_rows)],
    ["Columns Extracted", str(original_columns)]
]

table = Table(extract_table, colWidths=[2.5 * inch, 3.5 * inch])

table.setStyle(
    TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6)
    ])
)

story.append(table)


# ------------------------------------------------------------
# 4. DATA PROFILING
# ------------------------------------------------------------

story.append(
    Paragraph(
        "4. Data Profiling",
        heading_style
    )
)

story.append(
    Paragraph(
        "Data profiling was performed before transformation to "
        "understand the structure and quality of the raw dataset. "
        "The profiling process examined the dataset shape, column "
        "names, data types, missing values, duplicate records and "
        "statistical information.",
        body_style
    )
)

profiling_table = [
    ["Profiling Check", "Result"],
    ["Rows", str(original_rows)],
    ["Columns", str(original_columns)],
    ["Duplicate Rows", str(duplicate_count)],
    ["Columns With Missing Data",
     str(len(missing_values))]
]

table = Table(profiling_table, colWidths=[2.5 * inch, 3.5 * inch])

table.setStyle(
    TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6)
    ])
)

story.append(table)


# Missing values

if len(missing_values) > 0:

    story.append(
        Spacer(1, 10)
    )

    story.append(
        Paragraph(
            "Missing Value Details",
            ParagraphStyle(
                "SmallHeading",
                parent=styles["Heading3"],
                fontSize=11
            )
        )
    )

    missing_table = [
        ["Column", "Missing Records"]
    ]

    for column, count in missing_values.items():
        missing_table.append(
            [str(column), str(count)]
        )

    table = Table(
        missing_table,
        colWidths=[3.5 * inch, 2.5 * inch]
    )

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6)
        ])
    )

    story.append(table)


# ------------------------------------------------------------
# 5. TRANSFORMATION
# ------------------------------------------------------------

story.append(
    Paragraph(
        "5. Data Transformation",
        heading_style
    )
)

story.append(
    Paragraph(
        "The following transformations were applied to improve the "
        "quality and analytical usefulness of the dataset:",
        body_style
    )
)

transformations = [
    "Duplicate records were identified and removed.",
    "Leading and trailing spaces were removed from text fields.",
    "Order Date and Ship Date were converted to datetime format.",
    "Date parsing was standardized using day-first format.",
    "Missing Postal Code values were replaced with 'Unknown'.",
    "Numeric columns were checked for invalid negative and zero values.",
    "Order Year was created from Order Date.",
    "Order Month was created from Order Date.",
    "Order Month Name was created from Order Date.",
    "Order Quarter was created from Order Date.",
    "Order Year-Month was created for monthly analysis.",
    "Profit Margin was calculated using Profit divided by Sales."
]

for item in transformations:
    story.append(
        Paragraph(
            "• " + item,
            body_style
        )
    )


# ------------------------------------------------------------
# 6. BUSINESS DATA VALIDATION
# ------------------------------------------------------------

story.append(
    Paragraph(
        "6. Business Data Validation",
        heading_style
    )
)

story.append(
    Paragraph(
        "Numeric values were investigated to distinguish genuine "
        "business values from invalid data. Negative profit values "
        "were retained because they represent transactions where a "
        "loss occurred. Similarly, zero discount values were retained "
        "because they represent transactions where no discount was "
        "provided.",
        body_style
    )
)

validation_table = [
    ["Check", "Result"],
    ["Negative Profit Records", str(negative_profit)],
    ["Zero Discount Records", str(zero_discount)]
]

table = Table(
    validation_table,
    colWidths=[3.5 * inch, 2.5 * inch]
)

table.setStyle(
    TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6)
    ])
)

story.append(table)


# ------------------------------------------------------------
# 7. LOAD
# ------------------------------------------------------------

story.append(
    Paragraph(
        "7. Load",
        heading_style
    )
)

story.append(
    Paragraph(
        "After transformation, the cleaned DataFrame was exported "
        "as a new CSV file. The original dataset was preserved and "
        "the transformed data was saved separately.",
        body_style
    )
)

load_table = [
    ["Property", "Value"],
    ["Output File", "Global_Superstore_Cleaned.csv"],
    ["Rows Loaded", str(final_rows)],
    ["Columns Loaded", str(final_columns)],
    ["Load Status", "SUCCESS"]
]

table = Table(
    load_table,
    colWidths=[2.5 * inch, 3.5 * inch]
)

table.setStyle(
    TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6)
    ])
)

story.append(table)


# ------------------------------------------------------------
# 8. FINAL VALIDATION
# ------------------------------------------------------------

story.append(
    Paragraph(
        "8. Final ETL Validation",
        heading_style
    )
)

final_validation_table = [
    ["Validation", "Result"],
    ["Final Rows", str(final_rows)],
    ["Final Columns", str(final_columns)],
    ["Duplicate Records", str(final_duplicates)],
    ["Remaining Missing Values", str(final_missing)],
    ["ETL Status", "COMPLETED SUCCESSFULLY"]
]

table = Table(
    final_validation_table,
    colWidths=[3.5 * inch, 2.5 * inch]
)

table.setStyle(
    TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6)
    ])
)

story.append(table)


# ------------------------------------------------------------
# 9. CONCLUSION
# ------------------------------------------------------------

story.append(
    Paragraph(
        "9. Conclusion",
        heading_style
    )
)

story.append(
    Paragraph(
        "The Global Superstore dataset was successfully processed "
        "through an end-to-end ETL pipeline using Python and Pandas "
        "in Google Colab. The raw data was extracted and profiled, "
        "data quality issues were identified and appropriate "
        "transformations were applied. The resulting cleaned dataset "
        "was then loaded into a new CSV file and validated to ensure "
        "the ETL process completed successfully.",
        body_style
    )
)


# ------------------------------------------------------------
# BUILD PDF
# ------------------------------------------------------------

doc.build(story)

print("=" * 70)
print("PDF REPORT GENERATED SUCCESSFULLY")
print("=" * 70)
print("File:", output_pdf)
print("Location:", os.path.abspath(output_pdf))


# ============================================================
# DOWNLOAD PDF
# ============================================================

files.download(output_pdf)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 16.1 MB/s eta 0:00:00
======================================================================
PDF REPORT GENERATED SUCCESSFULLY
======================================================================
File: Global_Superstore_ETL_Report.pdf
Location: /content/Global_Superstore_ETL_Report.pdf